version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: frontend_container
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: backend_container
    working_dir: /backend/backend
    volumes:
      - ./backend:/backend/backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

networks:
  default:
    name: app-network
